### ISSUE TITLE
[Feat] 회원 타입 저장 기능, @EnumValid 추가

### ISSUE THREAD

**Issue by heeeeeseok** [Travel-in-nanaland/Back-end#17]
## 📝 Description
- `Member` 엔티티 type 필드 추가
  - `MemberType` enum 추가 
- 회원 타입 저장 기능 구현 
  - `MemberTypeController`
  - `MemberTypeService`
  - `MemberTypeRequest` - @RequsetBody
  - `SuccessCode`에 UPDATE_MEMBER_TYPE_SUCCESS 추가
  - `ControllerAdvice`에 HttpMessageNotReadableException 에러 처리 추가
- 회원 저장 기능 테스트 코드 작성
- EnumValid 애너테이션 추가

<br>

## ☑️ Todo
- [ ] `Member` 엔티티 type 필드 추가
- [ ] 회원 타입 저장 기능 구현 
- [ ] 회원 저장 기능 테스트 코드 작성 

<br>
