### ISSUE TITLE
[Chore] Swagger 설정 추가

### ISSUE THREAD

**Issue by jyajoo** [Travel-in-nanaland/Back-end#26]
## 📝 Description
> 기능 설명

<br>

## ☑️ Todo
- [x] swagger 의존성 추가
- [x] swagger 설정 파일 추가
- [ ] member controller에 사용해보기

<br>

## 💬 ETC
- 기타 사항
