### ISSUE TITLE
[Feat] mvp2 Review

### ISSUE THREAD

**Issue by jyajoo** [Travel-in-nanaland/Back-end#267]
## 📝 Description
> 기능 설명

<br>

## ☑️ Todo
- [ ] Review와 Post 매핑하기
- [ ] Review의 rating은 항상 정수일 예정이므로 변경해주기
- [ ] Review 좋아요 테이블 추가

<br>

## 💬 ETC
- 기타 사항
