### ISSUE TITLE
[Feat] JWT 생성 및 검증 부분 수정

### ISSUE THREAD

**Issue by jyajoo** [Travel-in-nanaland/Back-end#27]
## 📝 Description
> 기능 설명

<br>

## ☑️ Todo
- [x] JwtProvider에서 UserDetailsService의 loadUserByUsername 함수를 호출하는 부분 삭제
- [x] Jwt에 authorities 추가
- [x] 커스텀 어노테이션 추가

<br>

## 💬 ETC
- 기타 사항
