### ISSUE TITLE
[Feat] NaNa, 6대 카테고리 Entity 추가

### ISSUE THREAD

**Issue by heeeeeseok** [Travel-in-nanaland/Back-end#3]
### 엔티티 추가
- common
- common_trans
- nana
- nana_trans
- stay
- stay_trans
- market
- market_trans
- festival
- festival_trans
- nature
- nature_trans
- experience
- experience_trans

### common > config 에 QuerydslConfig 파일 추가
<br>

## ☑️ Todo
- [x] common, common_trans 엔티티 추가
- [x] 6대 카테고리 Entity 추가
- [x] mariadb 의존성 추가 - main
- [x] h2 database 의존성 추가 - test
- [x] querydsl 의존성 추가
- [x] querydsl 설정 파일 추가

<br>

## 💬 ETC
stay 엔티티는 common 엔티티를 상속하고 
stay_trans 엔티티는 baseEntity를 상속합니다.
