### ISSUE TITLE
[Feat] 엔티티 형식 통일, 일부 필드 매핑 데이터 타입 변경

### ISSUE THREAD

**Issue by heeeeeseok** [Travel-in-nanaland/Back-end#9]
## 📝 Description
- @NoArgsConstructor에 `access = AccessLevel.PROTECTED` 추가
- @JoinColumn에 `name, nullable` 추가
- `@Column(columnDefinition = "TEXT")`로 데이터 타입 변경
  - `CommonTrans`의 content, address
  - `NanaTrans`의 content
- `@Column(columnDefinition = "VARCHAR(2048)")`로 데이터 타입 변경
  - `CommonTrans`의 address
  - `StayTrans`의 address
  - `Nana`의 imageUrl
  - `Common`의 imageUrl
  - `Festival`의 homepage
  - `Market`의 homepage
  - `Stay`의 homepage
- 매핑관계 `orphanRemoval = true` 삭제
- 빌더패턴 테스트코드

<br>

## ☑️ Todo
- [x] @NoArgsConstructor에 `access = AccessLevel.PROTECTED` 추가
- [x] @JoinColumn에 `name, nullable` 추가
- [x] @Column(columnDefinition = "TEXT")로 데이터 타입 변경
- [x] `@Column(columnDefinition = "VARCHAR(2048)")`로 데이터 타입 변경
- [x] 매핑관계 `orphanRemoval = true` 삭제
- [x] 빌더패턴 테스트코드

<br>
